FROM oven/bun:1

WORKDIR /usr/src/app

ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

RUN echo "Inside Docker: DATABASE_URL is $DATABASE_URL"

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./apps/web ./apps/web
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

RUN bun install && \
    cd packages/db && \
    bunx prisma generate && \
    cd ../.. && \
    bun run build

EXPOSE 3001

CMD ["bun","run","start:web"]
