FROM oven/bun:1

WORKDIR /usr/src/app

ARG DATABASE_URL
COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./apps/web ./apps/web
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

RUN bun install 
RUN cd packages/db && bunx prisma generate && cd ../..
RUN DATABASE_URL=${DATABASE_URL} bun run build

EXPOSE 3001

CMD ["bun","run","start:web"]