FROM oven/bun:1

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./apps/backend ./apps/backend
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

RUN bun install 
RUN cd packages/db && bunx prisma generate && cd ../..

EXPOSE 3000

CMD ["bun","run","start:backend"]